services:
  postgres:
    image: postgres:16
    container_name: de_postgres
    environment:
      POSTGRES_DB: de_test
      POSTGRES_USER: de_user
      POSTGRES_PASSWORD: de_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.0
    container_name: airflow

    depends_on:
      - postgres
    env_file:
          - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://de_user:de_password@postgres/de_test
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: "fj9gq0rwBecdW0OEwoe3u8gI65KPyCWhos6WAf38BY4="
      PYTHONWARNINGS: "ignore"
      PYTHONPATH: /opt/airflow/src

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./requirements.txt:/opt/airflow/requirements.txt

    ports:
      - "8080:8080"

    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com || true &&
      pip install -r /opt/airflow/requirements.txt &&
      airflow scheduler & exec airflow webserver
      "
volumes:
  postgres_data: